# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'get_latest_by': 'founded_date', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
